FROM alpine:latest
RUN apk --no-cache add ca-certificates mailcap
WORKDIR /app
COPY kiro-api-proxy-linux ./kiro-api-proxy
COPY web-vue/dist ./web-vue/dist
RUN chmod +x ./kiro-api-proxy

EXPOSE 8080
VOLUME /app/data

CMD ["./kiro-api-proxy"]
